twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        seasonsList: '@App\Twig\SeasonsExtension'
        quizzsList: '@App\Twig\QuizzsExtension'
        currentUser: '@App\Twig\CurrentUserExtension'
        charactersVIP: '@App\Twig\CharactersExtension'
when@test:
    twig:
        strict_variables: true


