twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        seasonsList: '@App\Twig\SeasonsExtension'
        favoris: '@App\Twig\FavorisExtension'
        quote: '@App\Twig\QuoteExtension'
when@test:
    twig:
        strict_variables: true


